name: 'Terraform Deployment'

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write # Essential for requesting the JWT token from Google

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Log into GCP using OIDC Workload Identity Federation
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/272907652960/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'tf-github-actions@project-495bdca4-ac50-4df5-bb6.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
